[tool.poetry]
name = "q"
version = "0.1.0"
description = ""
authors = ["Takanori Ishikawa <takanori.ishikawa@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.4"
regex = "^2024.5.15"
requests = "^2.32.2"
tqdm = "^4.66.4"
tensorflow = "==2.16.1"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"

[tool.poetry.scripts]
q = "q:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
